version: '3.8'
services:
  API:
    image: bookapplication
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ekene
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"

    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ekene
      - POSTGRES_DB=bookapp
      - POSTGRES_HOST_AUTH_METHOD=trust